### ISSUE TITLE
modifymedium no completion?

### ISSUE THREAD

**Issue by schlomo** [gryf/vboxmanage-bash-completion#1]
Hi,

thanks a lot for this completion script - big help.

I noticed that (at least on Ubuntu 16.04 with VirtualBox 5.0.18) there are no completions for `VBoxManage modifymedium`.

Would you happen to know how to fix that?

Kind regards,
Schlomo

**Comment by gryf** [comment]
I didn't do the update to VirtualBox 5.x yet, but I have plans to do that soon. Stay tuned :)

**Comment by gryf** [comment]
Latest version (tagged 5.0.18) of the script should fix your issue.
