### ISSUE TITLE
Implement easy support for VBoxManage aliases

### ISSUE THREAD

**Issue by xPh03n1x** [gryf/vboxmanage-bash-completion#13]
Thank you for creating this !!

I personally use an alias `vb`, instead of `VBoxManage` as it is much quicker to type.

Adding the autocompletion for `vb` can be quickly accomplished via:
```
complete -o default -F _VBoxManage vb
```
but someone else might prefer to have this working in a different alias. Hence my recommendation.

The script can support virtually any alias, without hardcoding, by extending the autocompletion to cover the script's name:
```
complete -o default -F _VBoxManage $(basename "${BASH_SOURCE[0]}")
```

This way, when people download the "VirtualBoxManage" autocompletion script, they can rename it to whatever they want and the autocompletion will work for the command with that name.

For instance, if your file is downloaded and saved as "myvb", the autocompletion will be available when `myvb` is typed in bash.

**Comment by gryf** [comment]
Thanks for the feedback! With commit 3404afa4418ec1 you can do exactly this. Enjoy!
